### ISSUE TITLE
Proposal management panel novelties

### ISSUE THREAD

**Issue by Xfolchf** [decidim/design#159]

**Comment by carolromero** [comment]
related to https://github.com/decidim/decidim/issues/1993

**Comment by javierarce** [comment]
Just to be sure, we are talking about this page, right? @carolromero, @decidim/product: 

<img width="1280" alt="screen shot 2018-01-17 at 16 08 59" src="https://user-images.githubusercontent.com/4933/35049598-d1f842f4-fba0-11e7-8680-0859af4cbdb4.png">

**Comment by xabier** [comment]
@javierarce Yes! That panel, with a search box as well an the possibility to select many and execute different actions on the selected ones

**Comment by javierarce** [comment]
Ok, here are some screens with the new interface (or, to seem the more comfortably, here: https://marvelapp.com/1331hdig)

This is a regular screen with nothing selected: 
![no selection](https://user-images.githubusercontent.com/4933/35161389-5beb58c0-fd40-11e7-81d1-129b43e06dd2.png)

The sorting of the columns is accomplished by clicking on the labels. The first time you click on one of them, makes the order descending, the second click, ascending.

This solution comes from discourse forums and allow us to have a minimal interface without cluttering the UI (I've tried other options like having a filter line, having the up and down triangles visible all the time… but they complicate the interface).

![sort](https://user-images.githubusercontent.com/4933/35161403-67692bbe-fd40-11e7-99ec-8ac7cac12363.png)

Once we select one or more rows, we show possible actions (in the image a delete button, but we could have other actions)

![n selected](https://user-images.githubusercontent.com/4933/35161570-e8fc2636-fd40-11e7-94ae-7d8f86d52f2f.png)

![all selected](https://user-images.githubusercontent.com/4933/35161621-05035408-fd41-11e7-8e20-76a269eabefd.png)

Finally, the search and filter options (both of them are already implemented). Optionally, in case there's an active search, the message in read will appear to allow removing the applied filters and search term:
![n selected](https://user-images.githubusercontent.com/4933/35161665-293eaac0-fd41-11e7-8913-91669e91d58c.png)

**Comment by xabier** [comment]
@javierarce brilliant!

Can we ask something else, it is just one more step: there are different actions that can be performed other than "delete", would it be possible to design something that accommodates different actions? or just they simply appear as different buttons next to Delete? If so, should we define a color (say green) for those actions that are not negative (like "delete") or creative (like "new") but involve transformations (like "change category", "approve", "move", etc.)?

**Comment by javierarce** [comment]
Thanks!

Regarding your last suggestion: absolutely. My idea in case we had several different actions for a give set of items was to have a selector like this:

![actions](https://user-images.githubusercontent.com/4933/35218255-407687ce-ff6e-11e7-8cb8-b880231a10f1.png)

Upon clicking the button we would show a list with all the possible actions (we can use the same design as we have now for the list)

**Comment by xabier** [comment]
Excellent! :smile:

**Comment by javierarce** [comment]
Just saw this PR https://github.com/decidim/decidim/pull/2585 … I'll update this issue with the right placement of the category form with the new design.

**Comment by javierarce** [comment]
Here's the solution for the "recategorization" of items. To save space we could also put the remove button inside of the list of available actions:

![apply categories](https://user-images.githubusercontent.com/4933/35505256-d9868ed8-04e5-11e8-805d-5a761489601e.png)

![actions](https://user-images.githubusercontent.com/4933/35505255-d9393930-04e5-11e8-9cc1-5173a94afc57.png)

**Comment by xabier** [comment]
looks great!

**Comment by agustibr** [comment]
:+1: will use it in issue decidim/decidim#2291
