### ISSUE TITLE
CTA Participatory Process Home

### ISSUE THREAD

**Issue by Xfolchf** [decidim/design#161]

**Comment by javierarce** [comment]
Here's our proposal for the CTA:

![cta](https://user-images.githubusercontent.com/4933/33711743-54a263a0-db45-11e7-98f1-3c341b841423.png)

The button will link to the current phase when there's an action users can do (vote or support, read, RSVP, etc.). For those cases where there isn't a clear action (for example, a return phase that's just started), we suggest to send the users to the phase description in the list of phases.

cc: @decidim/product

**Comment by xabier** [comment]
thanks @javierarce once we complete identified improvements like this one, we should iterate with participat-tests, right now this looks good to me.

**Comment by Crashillo** [comment]
PR decidim/decidim#2440

**Comment by mrcasals** [comment]
As @josepjaume [said in the PR](https://github.com/decidim/decidim/pull/2440#issuecomment-355900144):

> Hi! Not sure how can we implement this, as a process can have many components and any component several call to actions. Have you thought about an admin interface for this?

I don't think we can infer the action from the code directly, as some features might not care about steps. I agree we should have an admin interface for this, even if it's a dropdown for each step somewhere, but this needs to be set by the user and not inferred by the code IMHO.

**Comment by mrcasals** [comment]
PR has been merged, should we close this?

**Comment by xabier** [comment]
:+1:
