### ISSUE TITLE
Proposal creation wizard

### ISSUE THREAD

**Issue by Xfolchf** [decidim/design#162]
* Follow this issue for specs: decidim/decidim#2286

**Comment by furilo** [comment]
Also something we may start working on @decidim/product

**Comment by xabier** [comment]
The proposal creation wizard already exists at https://github.com/decidim/decidim-initiatives that needs to be de departure point. Feel free to re-design departing from that

**Comment by xabier** [comment]
Follow this issue for specs: decidim/decidim#2286

**Comment by agustibr** [comment]
Hi @decidim/lot-px, you can see screenshots of each step in the PullRequest https://github.com/decidim/decidim/pull/2331

**Comment by javierarce** [comment]
Hi! Here's my proposal for the… Proposal Wizard :) As we talked on Monday, we should offer a similar experience in both the Initiative wizard and this one, hence the redesign.

https://marvelapp.com/7a8i4a4

I've reduced the number steps to just three (Create, Compare & Publish) by adding the category and identity fields on the first step, but if this change implies lots of changes or if you feel that those two fields add too much friction to the creation process, we could have 4 steps instead.

**Comment by xabier** [comment]
hi @javierarce I very much like the result, but here is an explanation as to why we need 4 steps and cannot merge 1st and 3rd. In some cases step 3 might require a to add much more than category and identity, for example other fields might require to add images, attachment, and other data. So our original idea was to ask for the basic information in step 1, then compare, then complete with additional fields, then confirm. 

@decidim/product what do you think?

For the rest it looks excellent except for one thing: I think the button for selecting or ignoring the similar proposals has to be on top, because if there are many similar proposal it might be confusing for the participant, this we discussed with @decidim/lot-mods last monday. The bottom button is good and explanatory but if I have to search for it I might be confused about having just created a proposal and not knowing what I have to do with different proposals been shown to me.

**Comment by carolromero** [comment]
> In some cases step 3 might require a to add much more than category and identity, for example other fields might require to add images, attachment, and other data. So our original idea was to ask for the basic information in step 1, then compare, then complete with additional fields, then confirm.

Yes, that's what we agreed, and that's also the standard flow in other iniatiatives platforms.

> The bottom button is good and explanatory but if I have to search for it I might be confused about having just created a proposal and not knowing what I have to do with different proposals been shown to me.

IMO it makes sense leave the button at the bottom, we tend to scroll-down looking for the action button. Also according to @javierarce's comment in the mockup: "Whenever a user selects a proposal, the scroll moves slowly to the end of the form so they can click the button." If it behaves like this, I don't think is too confusing.

However my concerns about this step being potentially confusing are related to the way similar proposals are displayed. Maybe it would be better to use another cards view in this step.

To put it with an example, this is how Petitions in the UK Gov site look:

![imagen](https://user-images.githubusercontent.com/23509895/34294139-67711468-e707-11e7-8704-d492d77576e5.png)



And similar petitions are displayed like this (see https://petition.parliament.uk):
![imagen](https://user-images.githubusercontent.com/23509895/34294295-19eff47e-e708-11e7-9b69-df29f302fd8d.png)

By using a different card view they avoid the confusion of browsing through the main page. So, maybe using a single row in this Step, like in the budgets view, would help?
https://decidim-design.herokuapp.com/projects-budget/

What do you think @javierarce @decidim/product ?

**Comment by javierarce** [comment]
Here's the proposal with your feedback applied, @carolromero: I think you were absolutely right to simplify the process. The result it's not only more easy to understand, but it also reduces the required javascript logic of the previous version.

Here's the step #2 updated with the new cards, new copy for the notification on top and a counter in the header ("Propuestas similares (4)"). I've also updated the mockup inside https://marvelapp.com/7a8i4a4

![proposal_step_2](https://user-images.githubusercontent.com/4933/34949778-66b5f184-fa11-11e7-8df7-734821d3c8b5.png)

**Comment by agustibr** [comment]
@javierarce great design! 
Where can I find the final design in html so i can implement it in #2286, is it available?

**Comment by furilo** [comment]
Hi @agustibr we expect to deliver this early next week.

**Comment by arnaumonty** [comment]
@javierarce @agustibr the text of the action "Continuar sin seleccionar una propuesta" should say something clear as "Mi propuesta is diferente" as UK petitons have.

**Comment by javierarce** [comment]
+1 @arnaumonty yeah, the text you propose is better. I'll change it in the mockups, thanks!

**Comment by agustibr** [comment]
@javierarce I don't know if you have taken into account these two cases:

+ in the second step, when similar proposals are not found
+ In the first step, when there is a draft <sup>1</sup>, I have two proposals:
   1. that the form is already filled (with the draft data)
   2. that a button to edit the draft appears

<sup>1</sup>: A draft is created when you have previously gone through the first and second step, and for whatever reason you do not pass the third step, and left the creation of the new proposal.

cc: @decidim/product

**Comment by javierarce** [comment]
For the first point you mention:  we can just send the user to the following step.

For the second point you mention, the first solution looks good to me (it's similar to the gmail draft approach or how it works when you don't finish publishing a tweet and reload the page).

**Comment by agustibr** [comment]
@javierarce I agree with your response
