### ISSUE TITLE
M Medium-sized card 

### ISSUE THREAD

**Issue by Xfolchf** [decidim/design#168]

**Comment by furilo** [comment]
@decidim/product should we start with all cards review? (at least the small and medium ones, which I think it's more or less clear)

**Comment by xabier** [comment]
@furilo yes, lets start, the best way to proceed would be to start with proposals, with is the most complex, and the start re-designing the rest of cards for spaces and components.

**Comment by javierarce** [comment]
Moving this issue over here: https://github.com/decidim/decidim/issues/2705
