### ISSUE TITLE
Design for blog

### ISSUE THREAD

**Issue by xabier** [decidim/design#174]
#### :tophat: User Story

The decidim-module-blog needs some input from @decidim/lot-px :+1: 

- [ ] Icon for Blog
- [ ] Blog home
- [ ] Blog cards (M size)

@decidim/lot-mods already has mockups but need feedback

#### :pushpin: Related issues

https://github.com/decidim/decidim-module-blogs

**Comment by xabier** [comment]
@decidim/lot-mods , @isaacmg410 please add screenshots here

**Comment by isaacmg410** [comment]
<img width="1278" alt="captura de pantalla 2017-12-04 a las 16 17 46" src="https://user-images.githubusercontent.com/28536082/33559988-ced11254-d90e-11e7-8789-deecfda2ad00.png">
<img width="1277" alt="captura de pantalla 2017-12-04 a las 16 16 38" src="https://user-images.githubusercontent.com/28536082/33559989-cf479f0a-d90e-11e7-8c59-b64a3710b171.png">
<img width="1280" alt="captura de pantalla 2017-12-04 a las 16 16 54" src="https://user-images.githubusercontent.com/28536082/33559991-cf8920ce-d90e-11e7-89cd-47a94556763a.png">
<img width="1278" alt="captura de pantalla 2017-12-04 a las 16 17 03" src="https://user-images.githubusercontent.com/28536082/33559993-d0411fda-d90e-11e7-9b62-5e1682088224.png">
<img width="1278" alt="captura de pantalla 2017-12-04 a las 16 17 35" src="https://user-images.githubusercontent.com/28536082/33559994-d0ff05cc-d90e-11e7-92fe-cfdc78a5479e.png">

**Comment by javierarce** [comment]
Just to give some visibility on this task (we'll show more screens in the coming days), here's a quick proposal for the home of the blog:

![blog_home](https://user-images.githubusercontent.com/4933/33841049-e51a1cbc-de96-11e7-98cf-28f4eba7898e.png)

**Comment by javierarce** [comment]
And some questions (I had a look to the repo, but I'd like to be sure of future plans):

- Are we planning to allow uploading images?
- And other kind of assets? (PDFs, for example)
- Will it be possible to have more than one author per post? 
- Are all posts public by default or will it be possible to have private ones?

**Comment by isaacmg410** [comment]
@xabier @javierarce, I'm looking to de design and it looks nice, but I've some doubts.
For an MVP, the author is not be visible on the public side, So I understand that the author in the design that has happened should not be seen, right?

On the right sidebar, what posts should be displayed? the previous to those that are currently displayed?

**Comment by isaacmg410** [comment]
@javierarce another question, where I can find the HTML of that page? I've been looking at https://github.com/decidim/design and I can't find it

**Comment by javierarce** [comment]
> @javierarce another question, where I can find the HTML of that page? I've been looking at https://github.com/decidim/design and I can't find it

@isaacmg410 it's not done yet (at least to my knowledge). What we are showing at this point it's just design.

> the author is not be visible on the public side, So I understand that the author in the design that has happened should not be seen, right?

Sorry, but I'm not following you… what do you mean? 

> On the right sidebar, what posts should be displayed? the previous to those that are currently displayed?

Yes, that was the initial idea. We could show the, for example, 7 previous articles to the ones we are showing on the left side. 

But maybe it would be more interesting for users to see a list of the posts/articles with more activity (comments or visits).

**Comment by isaacmg410** [comment]
@xabier, In a meeting we had, it was said that the author of the post was only to have proof of his author in the BackOffice. Do you want it visible on the FrontEnd?

> Yes, that was the initial idea. We could show the, for example, 7 previous articles to the ones we are showing on the left side.
> But maybe it would be more interesting for users to see a list of the posts/articles with more activity (comments or visits).

For and MVP, We show the 7 previous articles to the ones we are showing on the left side, do you think it's okay?

**Comment by mrcasals** [comment]
If I'm on the first page of posts and see the next 7 posts on the sidebar, and then I visit page 2, then I'll see those 7 posts again, which is weird (at least IMHO). If my opinion is valuable here, I'd go for showing the top commented posts 😄

**Comment by javierarce** [comment]
Well, none said that we would show the same past 7 articles over and over :)… we could show the 7 previous articles to the ones we are already displaying in the cards. 

But since we are already paginating at the bottom, maybe the best and more straightforward solution would be: 

- Show the top commented posts
- Show a link to the archive

**Comment by javierarce** [comment]
Regarding the "icon for the blog" task, my suggestion would be to use an icon similar to the one we are using for proposals, and modify the latter.

Here's a mockup of the proposed icons (in case we pick one we'd create them using the same style as the ones we already have).

![blog_icon](https://user-images.githubusercontent.com/4933/33883820-9fdcc800-df3d-11e7-9fc4-0c053d887fae.png)

**Comment by xabier** [comment]
Hi folks, take into account that we don't really expect an intensive use of this feature. Most processes or spaces where blog will be used will rarely produce more than 3-7 posts. If this helps for design.

@isaacmg410 we want author to display on front-end.

@javierarce nice idea to re-design proposal ico. I lke the second of the suggested proposals. I think the final icon might be best suited for other purposes.

in general I am not sure what is better to display on the right column but I agree with what @mrcasals says. Considering the non-intensive use of this component whatever works better (most commented is a good idea).

**Comment by isaacmg410** [comment]
@xabier @javierarce @mrcasals How or what is shown in the view if in the Blog feature, the comments are not enabled?

**Comment by xabier** [comment]
@isaacmg410 sorry I don't understand :(

**Comment by javierarce** [comment]
I think he meant: what should we show in the "top commented posts" if comments aren't enabled. Maybe we could label the column as "Posts with more activity" and use other metric in that case, like number of visits (I know it's a tricky one, because the posts with more visits will attract even more visits if we place it on top of the column)

**Comment by javierarce** [comment]
And here are the rest of the screens of the blog (archive and posts): https://marvelapp.com/49e4e7d. We've also added a subscription button that didn't appear in our first design.

I think the designs are pretty self explanatory, but let us know if there are any questions.

**Comment by xabier** [comment]
Ok, thanks for the clarification @javierarce . As I have previously said, I don't think we are going to have that many posts, ever, or very rarely, so it doesn't really bother me, but a solution is needed so I would show: most recent (in case the column stays there when reading full blog post). Most viewed is hard to track right now, would require too much development at this stage.

I am not sure the right column is going to have much value really. I wouldn't bother much with it, also I am worried about how is it going to display on mobile

**Comment by javierarce** [comment]
"I am worried about how is it going to display on mobile"

You mean that section specifically or the whole blog?

> I would show: most recent (in case the column stays there when reading full blog post).

Ok :)

**Comment by xabier** [comment]
> And here are the rest of the screens of the blog (archive and posts): https://marvelapp.com/49e4e7d. We've also added a subscription button that didn't appear in our first design.

Thanks @javierarce , nice job!

An important point here. All the card-displays need to follow a rather similar structure (meetings, proposals, blogs, etc.). There are some things I miss from the marvelapp mockups you provided:
1. I think we should include the author
2. Some information about the context of the post (in which process, organ, etc. it was posted): here I am thinking on displaying the cards on the home page, or receiving notifications or embedding it so it displays out of context.
3. Action buttons: adhere, follow and comment (although this can be accessed from the )
4. Category

**Comment by xabier** [comment]
> "I am worried about how is it going to display on mobile" You mean that section specifically or the whole blog?

The right column with the "most commented" or "most recent" posts

**Comment by javierarce** [comment]
Oh, that's true, the cards in the archive doesn't look consistent. I forgot to replace them with the new designs we worked on this week. I've fixed that now. I'll add the categories and rest of the missing details on Monday.

**Comment by xabier** [comment]
@javierarce :+1:

**Comment by isaacmg410** [comment]
@javierarce @carolromero Hi guys, I have seen that in the [Issue](https://github.com/decidim/decidim/issues/2365#issuecomment-352497808) you are talking about the automatic synchronization of design. As I said on Monday, I need the HTML this morning to be able to have something visible on Friday. 
Can I have the HTML of the BLOG even if the issue is not closed?
Thanks in advance

**Comment by furilo** [comment]
Mmm... difficult on our part. I propose that you create a basic HTML reusing other styles so you can build the thing, and then we can enter to apply the final styles.

**Comment by isaacmg410** [comment]
@xabier The following points are not clear to me:

1. Who creates the HTML? We? and then PX enter to apply the final styles? Or we apply the design when PX has done it and the [issue](https://github.com/decidim/decidim/issues/2365) of automatic styles synchronization is closed?

2. Looking at the designs, There are things that need to be clarified
- Should user be able to follow the blog and receive notifications?
- Can admin categorize posts? If so, are categories the same as the process?
- Does a blog archive have to exist?

Thanks

**Comment by furilo** [comment]
Normally, we'd create the HTML and the styles and the you'd integrate. But since we don't have the new decidim-design ready yet I propose you create your view with basic HTML and then we finish it. The other alternative is that you wait for the new decidim-design app to get finished, for us to start using it, which will take a little bit I guess... but that surely won't happen this morning.

**Comment by xabier** [comment]
hi @isaacmg410 

> Who creates the HTML? We? and then PX enter to apply the final styles? Or we apply the design when PX has done it and the issue of automatic styles synchronization is closed?

We have to patch untill we have the full system nicely running. If you can make the html now it would be great, just don't waste much time with it, @decidim/lot-px will come latter and do it properly. As @furilo explained they are currently working a having a nice design-dev framework to be more agile soon.

>    Looking at the designs, There are things that need to be clarified
> Should user be able to follow the blog and receive notifications?

Yes, please check this decidim/decidim#2334

> Can admin categorize posts? If so, are categories the same as the process?

Yes, and yes. Admins and blog content creators must be able to categorize content **with** the same categories inherited from the space-instance the blog belongs to.

> Does a blog archive have to exist?

Yes, the behaviour of this archive is like any other card collection (e.g. meetings or proposals)

![image](https://user-images.githubusercontent.com/537284/34207899-9ccf0c04-e58c-11e7-9910-fd1d683b29e5.png)

... please call @decidim/product instead or @xabier so other product people can also guide you :)

**Comment by carolromero** [comment]
Hi @isaacmg410,

Considering what @furilo said, I'd go with basic HTML to deliver something on Friday, and when the synchronization of styles is ready, let PX finish the work.

Regarding your questions:

> Should user be able to follow the blog and receive notifications?

Yes, he should, but I understand this depends on this [issue](https://github.com/decidim/decidim/issues/2334), so it will take a while to get it ready

> Can admin categorize posts? If so, are categories the same as the process?

Yes, an admin can assign categories. At first glance it makes sense to me to use the same categories as the process, but I don't have a strong opinion on this.

> Does a blog archive have to exist?

Maybe in the future, but not for an MVP.

**Comment by carolromero** [comment]
Ups crossed posts, but I guess both @xabier and I are saying the same ;)

**Comment by xabier** [comment]
@carolromero I agree more with you than I do with myself! :smile:

**Comment by javierarce** [comment]
Hi! We are about to start working on the HTML for this feature, do we have green light to implement these designs? Our main concern are the cards that appear in the archive section: https://marvelapp.com/49e4e7d

**Comment by xabier** [comment]
All good @javierarce , just one thing, but this might not affect design: on the left side of the archive we should have the regular filters that proposals or meetings have: with the category filter, etc. But this is already designed.

**Comment by Crashillo** [comment]
PR ready to be reviewed decidim/decidim#2430

**Comment by xabier** [comment]
Nice one @crashillo :+1:

**Comment by josepjaume** [comment]
Since the PR decidim/decidim#2430 is merged, can we close this?

**Comment by xabier** [comment]
done
