### ISSUE TITLE
Change icon for survey component

### ISSUE THREAD

**Issue by xabier** [decidim/design#175]
# This is a Feature Proposal

[Users demand we change the icon for the Survey component](https://meta.decidim.barcelona/processes/roadmap/f/122/proposals/12189) because we currently use the Information icon (the same we use for Pages). Since we use the [useiconic icon set](
https://useiconic.com/open) set for Decidim I think the icon clipboard can be well identified with a survey:

![image](https://user-images.githubusercontent.com/537284/34064923-42aace12-e1fd-11e7-9834-e312b1db91e7.png)

@decidim/lot-px anything to add?

**Comment by mrcasals** [comment]
As stated in https://github.com/decidim/decidim/issues/2390, the surveys icon that appears in the design showcase is already similar to the one @xabier suggests. I've stated how to update in the the related issue.

**Comment by mrcasals** [comment]
Note that the component icons do not use iconic icons, and were design directly for Decidim:

http://decidim-design.herokuapp.com/pattern-library/ (see "Iconos" section)

**Comment by mrcasals** [comment]
Closed by https://github.com/decidim/decidim/pull/2433.
