### ISSUE TITLE
Design for document manager on participatory processes

### ISSUE THREAD

**Issue by arnaumonty** [decidim/design#176]
# This is a Feature Proposal
It is needed a design for document manager

#### :tophat: Description
In order to have sorted the documents the improvements in document manager developed in #2274 include folders and documents.The design provided by default is shown below but it is needed a better design for the use case when we have several documents and folders to avoid a huge page and infinite scroll. Maybe a solution would be a drop-down for each folder or something similar.

![image](https://user-images.githubusercontent.com/3855859/34676940-cefb63ce-f48e-11e7-8b22-59e892ab5276.png)

**Comment by xabier** [comment]
My suggestion is:

* that documents get an icon on the left of the small display card, when they are directly downloadable and are a single document.
* when they are collections a folder is shown instead of the document-icon

We don't need much design for this. Do we?

**Comment by javierarce** [comment]
Here's my proposal: instead of using another card for the folders, I suggest that we use collapsable areas instead (this has also the added benefit of not needing a new icon to represent folders) 

![folders](https://user-images.githubusercontent.com/4933/35055380-61fe49ee-fbaf-11e7-8526-b17803d829cb.png)

https://marvelapp.com/7dj0j57

**Comment by xabier** [comment]
Simple and effective! :+1:

**Comment by Crashillo** [comment]
Included in decidim/decidim#2394

**Comment by arnaumonty** [comment]
@decidim/lot-mods @rbngzlv the design is ready.

**Comment by xabier** [comment]
Nice! :smiley: I will close this issue.
