### ISSUE TITLE
Revision of new special icons

### ISSUE THREAD

**Issue by javierarce** [decidim/design#177]
Create or pick icons for the new sections (assemblies, sortition, initiatives, consultation, etc.).

**Comment by javierarce** [comment]
Here's my proposal for the initiatives, assemblies, sortition, consultation.

![icons](https://user-images.githubusercontent.com/4933/35111785-5b41c5cc-fc7c-11e7-854e-e5530bdf8739.png)

I've also added a new one for videos (I've seen that some proposals use the "information" icon for this), plus added the icons for both the blog and proposals.

cc: @decidim/product

**Comment by xabier** [comment]
:heart: 

I find a problem with assemblies: it might be confused with a debate, assemblies are organs are groups of people, working groups, decision making groups, like councils, etc.

**Comment by mrcasals** [comment]
Then maybe showing a lot of people for the assemblies icon? I don't know if you can get so much detail in an icon this size, though, but it's the only thing that comes to mind to differentiate assemblies from debates.

Note that debates' icon is a single speech bubble:

![](https://i.imgur.com/s4F0CCf.png)

**Comment by javierarce** [comment]
Well spotted, @mrcasals. 

I like your suggestion, so what about using something like this: 

![screen shot 2018-01-22 at 13 07 16](https://user-images.githubusercontent.com/4933/35220071-41f774f8-ff75-11e7-917a-2f23de3b366d.png)

Probably the one in the bottom, right? The one on top could be confused with the idea of "talking or debating".

**Comment by javierarce** [comment]
Here's a small view of the icon: 
![screen shot 2018-01-22 at 13 09 10](https://user-images.githubusercontent.com/4933/35220136-7918d760-ff75-11e7-8b8a-fa1626ab8bac.png)

**Comment by xabier** [comment]
Mmmmm. How about "people" (dots) around a circle? Three people don't really make for an assembly an these icons resemble two parents with a baby (or is it just me?)

**Comment by javierarce** [comment]
Haha, you are right, but we could make the faces of the same size.

Ok, let's try with a more abstract idea as you suggest: 
<img width="90" alt="screen shot 2018-01-22 at 15 28 11" src="https://user-images.githubusercontent.com/4933/35225571-08e6d1d6-ff89-11e7-915e-c3f3aa1a4e9c.png">

**Comment by mrcasals** [comment]
First think that came to mind on seeing the last suggestion:

![](http://moziru.com/images/drawn-doughnut-bart-simpson-10.jpg)

**Comment by xabier** [comment]
That goes in the right direction. Now if it doesn't look like a guns bullet wheel ... :smile:

**Comment by javierarce** [comment]
Hahaha. What about a rectangular table?

<img width="91" alt="screen shot 2018-01-22 at 15 39 04" src="https://user-images.githubusercontent.com/4933/35226060-691fe410-ff8a-11e7-80bd-5ea47c3dd267.png">

**Comment by mrcasals** [comment]
What about something like this?

![](https://cdn1.iconfinder.com/data/icons/support-set/512/04_forum.png)

**Comment by javierarce** [comment]
Ah, that's interesting… I think it conveys the idea of "gathering of people" a bit better than table idea (which for me is "people talking or debating" )

So maybe something like this?
<img width="148" alt="screen shot 2018-01-22 at 15 58 33" src="https://user-images.githubusercontent.com/4933/35227025-390b07de-ff8d-11e7-8a39-82edf03bdc0c.png">

**Comment by xabier** [comment]
> Ah, that's interesting… I think it conveys the idea of "gathering of people" a bit better than table idea (which for me is "people talking or debating" )

The whole idea of an assembly is "people talking or debating", something I don't like from the last icon is that a fundamental property of an assembly is that all members are equal, and the front guy seems the boss on this icon. I prefer an interation on the revolver :smile:

**Comment by javierarce** [comment]
Ok, another iteration of the "revolver" icon: rounded rectangular table + 6 pax

<img width="133" alt="screen shot 2018-01-25 at 12 32 58" src="https://user-images.githubusercontent.com/4933/35386323-ed0c307e-01cb-11e8-8be3-df4c0383c7f3.png">

**Comment by xabier** [comment]
Perfect!

**Comment by xabier** [comment]
hi, @javierarce have these new icons been applied?

**Comment by javierarce** [comment]
No, I think I forgot to move them to the @Crashillo's plate. 

By the way, someone has reorganized the columns in waffle and we've lost the columns we used in PX :/

**Comment by xabier** [comment]
> By the way, someone has reorganized the columns in waffle and we've lost the columns we used in PX :/

@Xfolchf can you check this please?

**Comment by Crashillo** [comment]
This issue should be closed. There's a PR https://github.com/decidim/decidim/pull/3207 already merged.
